controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        en: ''
        pl: '/pl'
        ru: '/ru'

api_controllers:
    resource: ../../src/Controller/API/
    type: annotation
    prefix: /api