#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# job_homepage:
#     path: /
#     controller: App\Controller\JobController::index

job_homepage:
    path: /{_locale}
    controller: App\Controller\JobController::index
    requirements:
        _locale: en|pl|ru
    defaults:
        template: job/index.html.twig
        _locale: '%locale%'

# app_logout:
#     path: /logout
#     methods: GET