App\Entity\Category:
    type: entity
    repositoryClass: App\Repository\CategoryRepository
    table: category
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        slug:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
            gedmo:
                slug:
                  separator: -
                  # style: camel
                  fields:
                    - name
    oneToMany:
        jobs:
            targetEntity: Job
            mappedBy: category
    manyToMany:
        affiliates:
            targetEntity: Affiliate
            mappedBy: categories