App\Entity\User:
    type: entity
    # repositoryClass: App\Repository\PostRepository
    table: user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    lifecycleCallbacks:
        prePersist: [ prePersist ]